spring:
  application:
    name: ticketingapp
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5433/cybertek
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

